# Window

WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 400
WINDOW_GEOMETRY = f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}"
WINDOW_BG_COLOR = "#1a242b"

# Logger

MAX_NUM_LINES = 24
FONT_FAMILY = "Consolas"
FONT_SIZE = 10
FONT_COLOR = "#f0f0f0"
FONT_BG_COLOR = "#131313"
LOGGER_WIDTH = 115
LOGGER_HEIGHT = 35
LOGGER_BORDER_COLOR = "#f0f0f0"

# Buttons

START_X = 860
START_Y = 35
STEP_Y = 45
BUTTON_COLOR = ["green", "red"]
PADDING = 15
